export const SET_IS_LOADING_FETCH = 'SET_IS_LOADING_FETCH';
export const SET_SUCCESS_MSG = 'SET_SUCCESS_MSG';
export const SET_ERROR_MSG = 'SET_ERROR_MSG';

export default {
  SET_IS_LOADING_FETCH,
  SET_SUCCESS_MSG,
  SET_ERROR_MSG,
};
