export const SET_USER_DATA = 'SET_USER_DATA';

export const SET_IS_SIGNUP_SUCCESS = 'SET_IS_SIGNUP_SUCCESS';
export const SET_IS_SIGNUP_ERROR = 'SET_IS_SIGNUP_ERROR';
export const SET_SIGNUP_ERROR_MESSAGE = 'SET_SIGNUP_ERROR_MESSAGE';
export const SET_SIGNUP_SUCCESS_MESSAGE = 'SET_SIGNUP_SUCCESS_MESSAGE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const RESET_SIGNUP_VALUES = 'RESET_SIGNUP_VALUES';

export const SET_IS_SIGNIN_ERROR = 'SET_IS_SIGNIN_ERROR';
export const SET_SIGNIN_ERROR_MESSAGE = 'SET_SIGNIN_ERROR_MESSAGE';
export const SET_IS_SIGNIN_LOADING = 'SET_IS_SIGNIN_LOADING';
export const RESET_SIGNIN_VALUES = 'RESET_SIGNIN_VALUES';

export default {
  SET_USER_DATA,
  SET_IS_SIGNUP_SUCCESS,
  SET_IS_SIGNUP_ERROR,
  SET_SIGNUP_ERROR_MESSAGE,
  SET_SIGNUP_SUCCESS_MESSAGE,
  SET_IS_LOADING,
  RESET_SIGNUP_VALUES,
  SET_IS_SIGNIN_ERROR,
  SET_SIGNIN_ERROR_MESSAGE,
  SET_IS_SIGNIN_LOADING,
  RESET_SIGNIN_VALUES,
};
