export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_IS_SIGNUP_SUCCESS = 'SET_IS_SIGNUP_SUCCESS';
export const SET_IS_SIGNUP_ERROR = 'SET_IS_SIGNUP_ERROR';
export const SET_SIGNUP_ERROR_MESSAGE = 'SET_SIGNUP_ERROR_MESSAGE';
export const SET_SIGNUP_SUCCESS_MESSAGE = 'SET_SIGNUP_SUCCESS_MESSAGE';
export const SET_IS_LOADING = 'SET_IS_LOADING';

export default {
  SET_USER_DATA,
  SET_IS_SIGNUP_SUCCESS,
  SET_IS_SIGNUP_ERROR,
  SET_SIGNUP_ERROR_MESSAGE,
  SET_SIGNUP_SUCCESS_MESSAGE,
  SET_IS_LOADING,
};
