export const SET_SUBSIDIARIES = 'SET_SUBSIDIARIES';
export const SET_SINGLE_SUBSIDIARY = 'SET_SINGLE_SUBSIDIARY';
export const REMOVE_SINGLE_SUBSIDIARY = 'REMOVE_SINGLE_SUBSIDIARY';

export const SET_JOBS = 'SET_JOBS';
export const SET_SINGLE_JOB = 'SET_SINGLE_JOB';
export const REMOVE_SINGLE_JOB = 'REMOVE_SINGLE_JOB';

export default {
  SET_SUBSIDIARIES,
  SET_SINGLE_SUBSIDIARY,
  REMOVE_SINGLE_SUBSIDIARY,
  SET_JOBS,
  SET_SINGLE_JOB,
  REMOVE_SINGLE_JOB,
};
